# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rasmus Berg Palm Blog
#email: rasmusbergpalm@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  description
baseurl: "" # the subpath of your site, e.g. /blog
url: "rasmusbergpalm.github.io" # the base hostname & protocol for your site
twitter_username: rasmusbergpalm
github_username:  rasmusbergpalm

# Build settings
markdown: kramdown
